name: Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      # Broken - waiting on https://github.com/replicate/setup-cog/pull/43
      # Replacing with manual steps
      # - name: Setup Cog
      #   uses: replicate/setup-cog@v2
      #   with:
      #     token: ${{ secrets.REPLICATE_API_TOKEN }}
      #     install-cuda: true
      ##########################################################
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        with:
          driver: "docker"
  
      - name: Install NVIDIA CUDA Toolkit
        uses: Jimver/cuda-toolkit@c569a95f0d4b94657205f07567f6a55aeedf9974 # v0.2.16

      - name: Setup Cog
        shell: bash
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/v0.9.8/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Log in to Replicate
        shell: bash
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo "Found REPLICATE_API_TOKEN in the environment; Authenticating..."
          echo $REPLICATE_API_TOKEN | cog login --token-stdin
      
      ##########################################################
      
      - name: Install Hugging Face CLI
        run: pip install huggingface_hub
  
      - name: Download model files
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          huggingface-cli download sciphi/triplex@d3c3a297391cb5609ff7f5350c426ed0908112da \
             --token $HF_TOKEN \
             --local-dir ./ \
             --include="*.json" \
             --include="*.safetensors" \
             --include="*.gguf" \
             --include="*.model" \
             --include=".gitattributes"

      - name: Build
        run: cog build
      
      - name: Push to Replicate
        run: cog push r8.im/patrickjm/schiphi-triplex
